sudo: required

language: python
python: 2.7

services:
- docker

before_install:
  - docker version
  - docker info
  - pip install docker-compose
  - sudo service docker restart ; sleep 10

script:
- docker build --pull -t tomdesinto/jenkins-dsl-ready:test .
- IMAGE_NAME=tomdesinto/jenkins-dsl-ready:test tests/run_tests.sh
